[package]
name = "dichotomy"
authors = ["baer <gerald.schoiber@ins.jku.at"]
version = "0.1.0"
edition = "2021"


[profile.release]
strip = true

[dev-dependencies]
rand = "0.8.5"

[[example]]
name = "simple"
